[tool.poetry]
name = "OpenOligo"
version = "0.1.0"
description = "An open-source platform for programmatically interacting with and managing Nucleic acid sequences synthesis processes."
license = "MIT"
authors = ["Satyam Tiwary <satyam@technoculture.io>"]
readme = "README.md"
keywords = ["DNA", "synthesis", "Kilobaser", "biology", "genetics", "open-source"]

[tool.poetry.scripts]
openoligo = 'openoligo.main:main'

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
flake8 = "^3.9.2"
black = "^23.3.0"
pylint = "^2.17.4"
mypy = "^1.3.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88

