---
- hosts: arm.local
  vars:
    ansible_user: ubuntu
    git_username: sutyum
    git_email: satyam@technoculture.io
    git_repository: technoculture/OpenOligo
    python_version: "3.9"
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes

    - name: Ensure openssh-server is present
      become: true
      apt:
        name: openssh-server
        state: present

    - name: Start and enable SSH service
      become: true
      systemd:
        name: ssh
        state: started
        enabled: yes

    - name: Install Python
      #become: true
      apt:
        name: python{{ python_version }}
        state: present

    - name: Install Python3 Development Libraries
      #become: true
      apt: 
        name: python3-dev
        state: present

    - name: Install Python distutils
      #become: true
      apt:
        name: python3-distutils
        state: present

    - name: Install Rust
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/env"
          # become: true
 
    - name: Source cargo env
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'source $HOME/.cargo/env'
        create: yes
          # become: true
    
    - name: Install Python dev and pip
      #become: true
      apt:
        pkg:
        - python3-dev
        - python3-pip
        state: present
    
    - name: Upgrade pip
      #become: true
      pip:
        name: pip
        state: latest
    
    - name: Install Poetry
      #become: true
      shell: curl -sSL https://install.python-poetry.org | python3 -

    - name: Install VS Code
      #become: true
      apt:
        name: code
        state: present

    - name: Install Jupyter and Jupyter Lab
      #become: true
      pip:
        name:
          - jupyter
          - jupyterlab

    - name: Install Git
      #become: true
      apt:
        name: git
        state: present

    - name: Set global Git credentials
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      loop:
        - { name: 'user.name', value: "{{ git_username }}" }
        - { name: 'user.email', value: "{{ git_email }}" }

    - name: Clone Git repository
      git:
        repo: 'https://github.com/{{ git_repository }}.git'
        dest: '/home/pi/{{ git_repository }}'
