name: Lint and Test OpenOligo

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.2
    - name: Install dependencies
      run: |
        poetry install
    - name: Lint with pylint
      run: |
        poetry run pylint openoligo
    - name: Test with pytest
      run: |
        poetry run pytest
    - name: Lint with flake8
      run: |
        poetry run flake8 openoligo
        #- name: Format with Black
        #  run: |
        #    poetry run black --check openoligo
